<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
	<PublishTrimmed>true</PublishTrimmed>

    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup>
    <Version>1.2.3.4</Version>
    <Authors>Aida Enna</Authors>
    <Company>Arks-Layer (Aida Enna)</Company>
    <Product>FFXIVMobile Companion</Product>
    <PackageId>FFXIVMobile_Companion</PackageId>
    <AssemblyVersion>127.0.0.1</AssemblyVersion>
    <FileVersion>127.0.0.1</FileVersion>
    <NeutralLanguage>en</NeutralLanguage>
    <Description>Modifies your FFXIV Mobile game install with language options and fixes!</Description>
    <Copyright>Copyright ©  2025</Copyright>
    <RepositoryUrl>https://github.com/Aida-Enna/FFXIVMobile_Companion</RepositoryUrl>
  </PropertyGroup>
</Project>
